# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Deploy Docs

on:
  workflow_run:
    workflows:
      - "Run Vitest for Hungry Hippo Game"
    types:
      - completed

permissions:
  actions: read
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure coverage dir is empty
        run: |
          rm -rf documentation/static/coverage
          mkdir -p documentation/static/coverage

      - name: Download coverage report from tests workflow
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: main.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: coverage-report
          use_unzip: true
          path: documentation/static/coverage

      - name: Verify downloaded files
        run: ls -laR documentation/static/coverage

      - name: Install
        run: cd documentation && yarn install

      - name: Deploy
        run: |
          export ORG_NAME=$(echo ${GITHUB_REPOSITORY%/*})
          export PROJECT_NAME=$(echo ${GITHUB_REPOSITORY#*/})
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd documentation && NODE_ENV="production" GIT_USER="github-actions[bot]" GIT_PASS="${{ secrets.GITHUB_TOKEN }}" yarn deploy
